### ISSUE TITLE
`compute_dea()` and `bootstrap_dea()` should accept `NULL` for `id` argument

### ISSUE THREAD

**Issue by ohjakobsen** [Riksrevisjonen/pioneeR#101]
Both `compute_dea()` and `bootstrap_dea()` should accept `NULL` as the value given to the `id` argument. While the user will have a column in their data for ID/DMU, there might be cases where this information is not available. In such instances, the ID should simply be calculated by assigning a row number.

**Comment by Aeilert** [comment]
Solved with #103.
