### ISSUE TITLE
Missing Malmquist table

### ISSUE THREAD

**Issue by Aeilert** [Riksrevisjonen/pioneeR#36]
When calculating the Malmquist index the output table dosen't show. 

![image](https://github.com/Riksrevisjonen/pioneeR/assets/8194990/abcc1047-47e4-45b9-8106-4cf7e8d6fef9)

A quick fix appears to be to replace `dataTableOutput('malm.render')` with `reactable::reactableOutput('malm.render')`

https://github.com/Riksrevisjonen/pioneeR/blob/bcf18d588f40f0c1525a0115e39b03bd84113e4f/inst/app/server.R#L870

But we might also want to take a closer look at how the table and tab is rendered.

**Comment by ohjakobsen** [comment]
I'll have a look and add a fix in the next PR.
