### ISSUE TITLE
Error if no suitable time period variables are found

### ISSUE THREAD

**Issue by ohjakobsen** [Riksrevisjonen/pioneeR#41]
If a given data set has duplicate firms, pioneeR assumes that we have time series data. However, if no suitable variables for the the time period are found (the app checks for numerical columns with values within the range 1900 to 2100), the user cannot select a variable as the time period variable, and an error is shown in the sidebar. This behavior should be changed to that the error is catched, and the user is properly informed. This is in particular a problem with data sets that do not include a firm ID, but that has unique observations. For a reproducible example, run:
```r
runPioneeR(x = rDEA::hospitals)
```

**Comment by Aeilert** [comment]
Just a comment here @ohjakobsen: I think we should change the behaviour of time period check to not only include YYYY years. The time period in a DEA analysis doesn't need to be year. So I think e.g. 1,2,3, ... should also be accepted. Several classic DEA datasets also code their years in YY format.
