### ISSUE TITLE
Bootstrap will fail if the LP program is not able to solve all units

### ISSUE THREAD

**Issue by ohjakobsen** [Riksrevisjonen/pioneeR#54]
For a given data set where the LP program is not able to solve the optimum value for each unit, the bootstrap function will fail with an error message in the `quantile`-function when the confidence intervals are constructed. This is due to missing values in the bootstrapped efficiency scores. We need to add checks and validations to the bootstrap function so that missing values are catched and handled, and the user is informed.

**Comment by Aeilert** [comment]
Yep. This seems like the error I saw in #49.
