### ISSUE TITLE
Replace `{productivity}` with custom code for Malmquist calculations

### ISSUE THREAD

**Issue by Aeilert** [Riksrevisjonen/pioneeR#81]
We need to talk about the Malmquist-tab before implementing this, but the underlying logic can build on #80.

**Comment by ohjakobsen** [comment]
We need to figure out if and if yes, how, we should support returns to scale other than CRS. We can implement our own function with support for CRS only as a first commit. Results should be similar to the app as it is today, as `{productivity}` only supports CRS.
